config/routes.rb
Rails.application.routes.draw do
  resources :regis do
    resources :comments
  end
  
  devise_for :users
  get 'home/index'
  root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :regi
end

app/models/regi.rb
class Regi < ActiveRecord::Base
    mount_uploader :picture, ImageUploader
    belongs_to :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @regi = Regi.find(params[:regi_id])
        @comment = @regi.comments.create(comment_params)
        redirect_to regi_path(@regi)
    end
    
    def destroy
        @regi = Regi.find(params[:regi_id])
        @comment = @regi.comments.find(params[:id])
        @comment.destroy
        redirect_to regi_path(@regi)
    end
    
    private
      def comment_params
          params.require(:comment).permit(:commenter, :body)
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
 
    @message2 = "Dongguk room saver!"
    @count = 3
    @explanation = "This message came from the controller."
  end
end

app/controllers/regis_controller.rb
class RegisController < ApplicationController
  before_action :set_regi, only: [:show, :edit, :update, :destroy]

  # GET /regis
  # GET /regis.json
  def index
    @regis = Regi.all
  end

  # GET /regis/1
  # GET /regis/1.json
  def show
  end

  # GET /regis/new
  def new
    @regi = Regi.new
  end

  # GET /regis/1/edit
  def edit
  end

  # POST /regis
  # POST /regis.json
  def create
    #Regi.create( picture: params[:picture])
    @regi = Regi.new(regi_params)

    respond_to do |format|
      if @regi.save
        format.html { redirect_to @regi, notice: 'Regi was successfully created.' }
        format.json { render :show, status: :created, location: @regi }
      else
        format.html { render :new }
        format.json { render json: @regi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regis/1
  # PATCH/PUT /regis/1.json
  def update
    respond_to do |format|
      if @regi.update(regi_params)
        format.html { redirect_to @regi, notice: 'Regi was successfully updated.' }
        format.json { render :show, status: :ok, location: @regi }
      else
        format.html { render :edit }
        format.json { render json: @regi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regis/1
  # DELETE /regis/1.json
  def destroy
    @regi.destroy
    respond_to do |format|
      format.html { redirect_to regis_url, notice: 'Regi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_regi
      @regi = Regi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def regi_params
      params.require(:regi).permit(:title, :housetype, :address, :deposit, :monthlyfee, :picture, :description, :managementfee, :phone)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/regis_helper.rb
module RegisHelper
end

app/views/home/index.html.erb
<head>
<style>
#video { 
    position: fixed;
    top: 50%;
    left: 50%;
    min-width: 100%;
    min-height: 90%;
    width: auto;
    height: auto;
    z-index: -100;
    -ms-transform: translateX(-50%) translateY(-50%);
    -moz-transform: translateX(-50%) translateY(-50%);
    -webkit-transform: translateX(-50%) translateY(-50%);
    transform: translateX(-50%) translateY(-50%);
}
  #bak{
    background-video:url('/Star3.mp4');
    background-size:cover;
  }
  @font-face{
    font-family: 'quaterback';
    src: url(quaterback.ttf) format('truetype');
  }
  @font-face{
    font-family: 'Charbroil';
    src: url(Charbroil.ttf) format('truetype');
  }
  #qtr{
    font-family: 'quaterback';
  }
  #chr{
    font-family: 'Charbroil';
  }
  .myheader{
    float: left;
    width: 100%;
    height: 150px;
  }
  .myheader2{
    float: left;
    width: 30%;
    height: 200px;
  }
  .leftMain{
    float: left;
    width: 50%;
  }
  .rightMain{
    float: left;
    width: 50%;
  }
</style>
</head>
  <video id="video" preload="auto" autoplay="true" loop="loop" muted="muted" volume="0">
      <source src="/star3.mp4">
</video>
<body id = "bak" >

<font color = "white">
  
  <div id='myheader'>
    <br>
    <center>
    <br>
    <font id ="qtr" size=7>
      DONGGUK'S ROOM SAVER
    </font>
    <br>
        <font id = "chr" size=4>
      We provide the best room for Dongguk University students.
    </font>
    </center>

  </div>
  <br /><br /><br /><br /><br /><br />
  <center>
    <% if user_signed_in? %>
    <% current_user.email %>
      <a href=<%= edit_user_registration_path %> title="edit information"><img src='contract.png' width = "100px",height="60px"></a>
      <a href=<%= destroy_user_session_path %> title="sign out">
      <img src='logout3.png' width = "100px",height="60px">
      </a>
    
    <% else %>
      <a href=<%= new_user_registration_path %> title="register"><img src='new-user.png' width = "100px",height="100px" alt="register"></a>
      <a href=<%= new_user_session_path %> title="sign in"><img src='key.png' width = "100px",height="100px" alt="sign in"></a>
    <% end %>
 

    <font id = "chr" size=6 color="#993b8b">
    </font>

    <a href=<%= regis_path %> title="search"><img src='loupe.png' width = "100px",height="100px" alt="search"></a>


  

    <font id = "chr" size=6 color="#993b8b">
    </font>

    <% if user_signed_in? %>
    <% current_user.email %>
      <a href=<%= new_regi_path %> title ="for sale/lease"><img src='rent.png' width = "100px",height="100px"></a>
    <% else %>
      <a href=<%= new_user_session_path %> title="for sale/lease"><img src='rent.png' width = "100px",height="100px"></a>
    <% end %>
    
    </center>
    
 
</font>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/regis/_form.html.erb
<head><style>
#video { 
    position: fixed;
    top: 50%;
    left: 50%;
    min-width: 100%;
    min-height: 90%;
    width: auto;
    height: auto;
    z-index: -100;
    -ms-transform: translateX(-50%) translateY(-50%);
    -moz-transform: translateX(-50%) translateY(-50%);
    -webkit-transform: translateX(-50%) translateY(-50%);
    transform: translateX(-50%) translateY(-50%);
}
</style></head>
  <video id="video" preload="auto" autoplay="true" loop="loop" muted="muted" volume="0">
      <source src="/earth.mp4">
</video>
<body>
<%= form_for(@regi) do |f| %>
  <% if @regi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@regi.errors.count, "error") %> prohibited this regi from being saved:</h2>

      <ul>
      <% @regi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Building_name , :style => 'color: white;'%><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :Residential_type , :style => 'color: white;'%><br>
    <%= f.text_field :housetype %>
  </div>
  <div class="field">
    <%= f.label :Address , :style => 'color: white;'%><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :Deposit , :style => 'color: white;'%><br>
    <%= f.number_field :deposit %>
  </div>
  <div class="field">
    <%= f.label :Monthly_fee , :style => 'color: white;'%><br>
    <%= f.number_field :monthlyfee %>
  </div>
  <div class="field">
    <%= f.label :Management_fee , :style => 'color: white;'%><br>
    <%= f.number_field :managementfee %>
  </div>
  <div class="field">
    <%= f.label :Description , :style => 'color: white;'%><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :Phone_number, :style => 'color: white;' %><br>
    <%= f.telephone_field :phone %>
  </div>
  <div class="field">
    <%= f.label :Room_picture, :style => 'color: white;' %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit :Submit %>
  </div>
<% end %>
</body>

app/views/regis/edit.html.erb
<h1><font id ="qtr" size=6 color="white">
EDIT PROPERTY.</font></h1>

<%= render 'form' %>

<%= link_to 'detail', @regi %>
<%= link_to 'back', regis_path %>
<%= link_to 'home', '/' %>

app/views/regis/index.html.erb
<head><style type = "text/css">
  #bak{
    background-image:url('/hubble.jpg');
    background-size:cover;
}
@font-face{
    font-family: 'quaterback';
    src: url(quaterback.ttf) format('truetype');
}
  #qtr{
    font-family: 'quaterback';
}

#tbr{
 border:2px solid #FFF;
 border-collapse:collapse;
}
#tdd{
 width:100px;
 border:1px solid #FFF;
 height:20px;
}
#thh{
 width:100px;
 border:1px solid #FFF;
 height:20px;
}
</style>
</head>
<script type="text/javascript" src="//apis.daum.net/maps/maps3.js?apikey=95459617d76c0dd8bb5edc6acf0ed818&libraries=services,clusterer,drawing"></script>

<script type = "text/javascript">
function Search() {
  var result = document.getElementById('result').value;
  var str = "http://map.daum.net/link/search/"
  str = str + result
    window.open(str, 'width=300, heigth=300')
}</script>

<body id = "bak" style="height:100%; width:100%">

<br> <center>
<h1><font id ="qtr" size=6 color="white">
DETECT A ROOM.</font></h1>
<font color = "white" size = "3px">
<table id = "tbr">
  <thead>
    <tr>
      <th id = "thh">Name</th>
      <th id = "thh">Type</th>
      <th id = "thh">Address</th>
      <th id = "thh">Deposit/Rent</th>
      <th id = "thh">Management_fee</th>
      <th id = "thh">Description</th>
      <th id = "thh">Phone_number</th>
      <th colspan="3"></th>
    </tr>
  </thead></font>

  <tbody><font color = "white">
    <% @regis.each do |regi| %>
      <tr align="center">
        <td id = "tdd"><%= regi.title %></td>
        <td id = "tdd"><%= regi.housetype %></td>
        <td id = "tdd"><%= regi.address %></td>
        <td id = "tdd"><%= regi.deposit %>/<%= regi.monthlyfee %></td>
        <td id = "tdd"><%= regi.managementfee %></td>
        <td id = "tdd"><%= regi.description %></td>
        <td id = "tdd"><%= regi.phone %></td>&nbsp;&nbsp;&nbsp;&nbsp;
        <td id = "tdd"><%= link_to 'Detail', regi, :style => 'color: #A566FF;' %>&nbsp;<%= link_to 'Edit', edit_regi_path(regi), :style => 'color: #6B66FF;' %>&nbsp;<%= link_to 'Delete', regi, method: :delete, data: { confirm: 'Are you sure you want to delete it?' }, :style => 'color: #F29661;' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br /><br />
<a href='/'><img src="home.gif" width="50" height="50" title="Go to home"></a>&nbsp;&nbsp;&nbsp;<% if user_signed_in? %>
    <% current_user.email %>
      <a href=<%= new_regi_path %>><img src='rent.png' width = "50",height="50"></a>
    <% else %>
      <a href=<%= new_user_session_path %> title="for sale/lease"><img src='rent.png' width = "50",height="50"></a>
    <% end %>
</font>

<br /><table boder = NULL>
<form name = "fm">
<tr border = NULL><th border = NULL><font color = "white", size = "3px">Address: </font></th>
  <th border = NULL><input type="text" id = "result" name = "result" size = "30" / ></th>
  <th border = NULL><input type = "image" src="daum2.png" width="80" height="80" onclick = "Search()" / title= "Search"></th></tr>
  <div id="result"></div>
</form></table></center>
</body>
<br />

app/views/regis/new.html.erb
<head><style>
  @font-face{
    font-family: 'quaterback';
    src: url('/quaterback.ttf') format('truetype');
  }
    #qtr{
    font-family: 'quaterback';
  }
</style></head>
<h1><font id ="qtr" size=7 color="white">
NEW LISTING.</font></h1>

<%= render 'form' %>

<%= link_to 'back', :back %>
<%= link_to 'home', '/' %>

app/views/regis/show.html.erb
<head><style>
#video { 
    position: fixed;
    top: 50%;
    left: 50%;
    min-width: 100%;
    min-height: 90%;
    width: auto;
    height: auto;
    z-index: -100;
    -ms-transform: translateX(-50%) translateY(-50%);
    -moz-transform: translateX(-50%) translateY(-50%);
    -webkit-transform: translateX(-50%) translateY(-50%);
    transform: translateX(-50%) translateY(-50%);
}
  @font-face{
    font-family: 'quaterback';
    src: url('/quaterback.ttf') format('truetype');
  }
    #qtr{
    font-family: 'quaterback';
  }
  #tbr{
 border:2px solid #FFF;
 border-collapse:collapse;
}
#tdd{
 width:500px;
 border:1px solid #FFF;
 height:20px;
}
#thh{
 width:500px;
 border:1px solid #FFF;
 height:20px;
}
#tdd2{
 width:100px;
 border:1px solid #FFF;
 height:20px;
}
  
</style></head>
  <video id="video" preload="auto" autoplay="true" loop="loop" muted="muted" volume="0">
      <source src="/satu.mp4">
</video>
<h1><font id ="qtr" size=6 color="white">
PROPERTY DETAIL.</font></h1>

<p id="notice"><%= notice %></p>
<font color="white">
<p>
  <% if @regi.picture.url.nil? %>
  <h5>No photos registered.</h5><br />
  <% else %>
  <img src="<%= @regi.picture.url %>" width="300px", height="200px">
  <% end %>
</p>

<p>
  <strong><font color="#9f8038">Building_name:</font></strong>
  <%= @regi.title %>
</p>

<p>
  <strong><font color="#9f8038">Residential_type:</font></strong>
  <%= @regi.housetype %>
</p>

<p>
  <strong><font color="#9f8038">Address:</font></strong>
  <%= @regi.address %>
</p>

<p>
  <strong><font color="#9f8038">Deposit:</font></strong>
  <%= @regi.deposit %>
</p>

<p>
  <strong><font color="#9f8038">Monthly_fee:</font></strong>
  <%= @regi.monthlyfee %>
</p>

<p>
  <strong><font color="#9f8038">Management_fee:</font></strong>
  <%= @regi.managementfee %>
</p>

<p>
  <strong><font color="#9f8038">Description:</font></strong>
  <%= @regi.description %>
</p>


<p>
  <strong><font color="#9f8038">Phone_number:</font></strong>
  <%= @regi.phone %>
</p>
<br />

<h4><font color="#9f8038">Comments</font></h4>
<table id = "tbr">
  <thead>
    <tr>
    <th id = "tdd2">Nickname</th>
    <th id = "thh">Comments</th>
    <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @regi.comments.each do |c| %>
    <tr>
      <td id = "tdd2"><center><%= c.commenter %></center></td>
      <td id = "tdd"><center><%= c.body %></center></td>&nbsp;&nbsp;&nbsp;
      <td><center><%= link_to 'Delete', [c.regi, c] , method: :delete, :style => 'color: blue;', data: { confirm: 'Are you sure you want to delete it?' } %></center></td>
    </tr>
  </tbody>
<% end %>
</table>
<br /><br />

<h4><font color="#9f8038">Write comment</font></h4>
<%= form_for([@regi, @regi.comments.build]) do |f| %>
 <p>
  <%= f.label :Nickname %>
  <br>
   <%= f.text_field :commenter %>
 </p>
 <p>
   <%= f.label :Comment %>
   <br>
   <%= f.text_area :body %>
 </p>
 <p>
   <%= f.submit "Submit" %>
 </p>
<% end %>
<br />
<%= link_to 'edit', edit_regi_path(@regi), :style => 'color: white;' %><br />
<%= link_to 'back', regis_path, :style => 'color: white;' %><br />
<%= link_to 'home', '/', :style => 'color: white;' %>
</font>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "log_in", new_session_path(resource_name), :style => 'color: white;' %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "sign_up", new_registration_path(resource_name), :style => 'color: white;' %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "forgot password?", new_password_path(resource_name), :style => 'color: white;' %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), :style => 'color: white;' %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), :style => 'color: white;' %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), :style => 'color: white;' %><br />
  <% end -%>
<% end -%>